const types = {
    REQUEST_ERROR: 'REQUEST_ERROR',

    USER_SET: 'USER_SET',
    USER_START_FETCHING: 'USER_START_FETCHING',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_SET_LOGIN: 'USER_SET_LOGIN',

    REPOSITORIES_ADD: 'REPOSITORIES_ADD',
    REPOSITORIES_CLEAN: 'REPOSITORIES_CLEAN',
    REPOSITORIES_START_FETCHING: 'REPOSITORIES_START_FETCHING',
    REPOSITORIES_NOT_FOUND: 'REPOSITORIES_NOT_FOUND',
};

export default types;
